language: csharp
sudo: required
dist: trusty
deploy:
  # provider: gae
  # keyfile: "Scheduler-3b87c61d431a.json"
  # project: "eng-mechanism-161715"
  on: deploy-settings
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
# install dotnet core
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
- sudo apt-get update && sudo apt-get install dotnet-dev-1.0.1
# Install gcloud
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
# Decrypt service account json file
- openssl aes-256-cbc -K $encrypted_4a7399281b85_key -iv $encrypted_4a7399281b85_iv -in Scheduler-3b87c61d431a.json.enc -out Scheduler-3b87c61d431a.json -d
# Activate gcloud
- gcloud auth activate-service-account --key-file Scheduler-3b87c61d431a.json
script:
- ./build.sh publish
